### ISSUE TITLE
Landing page: streamline login redirect

### ISSUE THREAD

**Issue by anmipa** [City-of-Helsinki/omahelsinki#75]
Works good and fine for MVP, needs some streamlining later on.

**Comment by igordavydsson** [comment]
Right now the user gets redirected to oboarding page, which redirects the user further to /mydata page if the user has account. Because of that we see the onboarding page for a split second, maybe seeing some loader instead during the time when omahelsinki figures out if user has an account or not would be a cleaner UX?
